<a href="https://colab.research.google.com/github/kevinmevada/Machine_learning_Projects/blob/main/Housing_sales_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing important libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

Read the excel file of housing data

In [3]:
housing_data = pd.read_excel(r'/HOUSEPRED.xlsx')
housing_data.head(30)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,yr_built
0,313000.0,3.0,1.50,NaN,7912,1.5,3,1340,0,1955
1,2384000.0,5.0,2.50,NaN,9050,2.0,5,3370,280,1921
2,342000.0,3.0,2.00,1930.0,11947,1.0,4,1930,0,1966
3,420000.0,3.0,2.25,2000.0,8030,1.0,4,1000,1000,1963
4,550000.0,4.0,2.50,1940.0,10500,1.0,4,1140,800,1976
5,490000.0,2.0,1.00,880.0,6380,1.0,3,880,0,1938
6,335000.0,2.0,2.00,1350.0,2560,1.0,3,1350,0,1976
7,482000.0,4.0,2.50,2710.0,35868,2.0,3,2710,0,1989
8,452500.0,3.0,NaN,2430.0,88426,1.0,4,1570,860,1985
9,640000.0,4.0,2.00,1520.0,6200,1.5,3,1520,0,1945
10,463000.0,3.0,1.75,1710.0,7320,1.0,3,1710,0,1948
11,1400000.0,NaN,2.50,2920.0,4000,1.5,5,1910,1010,1909
12,588500.0,3.0,1.75,2330.0,14892,1.0,3,1970,360,1980
13,365000.0,3.0,1.00,1090.0,6435,1.0,4,1090,0,1955
14,1200000.0,5.0,2.75,2910.0,9480,1.5,3,2910,0,1939
15,242500.0,3.0,1.50,1200.0,9720,1.0,4,1200,0,1965
16,419000.0,3.0,1.50,1570.0,6700,1.0,4,1570,0,1956
17,367500.0,4.0,3.00,3110.0,7231,2.0,3,3110,0,1997
18,257950.0,3.0,1.75,1370.0,5858,1.0,3,1370,0,1987
19,275000.0,3.0,1.50,1180.0,10277,1.0,3,1180,0,1983
20,750000.0,NaN,1.75,2240.0,10578,2.0,5,1550,690,1923
21,435000.0,4.0,1.00,1450.0,8800,1.0,4,1450,0,1954
22,626000.0,3.0,2.25,1750.0,1572,2.5,3,1470,280,2005
23,612500.0,4.0,2.50,2730.0,12261,2.0,3,2730,0,1991
24,495000.0,4.0,1.75,1600.0,6380,1.0,3,1130,470,1959
25,285000.0,3.0,2.50,2090.0,10834,1.0,4,1360,730,1987
26,615000.0,3.0,1.75,2360.0,7291,1.0,4,1360,1000,1948
27,698000.0,4.0,2.25,2200.0,11250,1.5,5,1300,900,1920
28,675000.0,5.0,2.50,2820.0,67518,2.0,3,2820,0,1979
29,790000.0,3.0,2.50,2600.0,4750,1.0,4,1700,900,1951

Removed Null values and replaced it with respective Median

In [4]:
import math
median_bedroom= math.floor(housing_data.bedrooms.median())
median_bathrooms= math.floor(housing_data.bathrooms.median())
median_sqft_living= math.floor(housing_data.sqft_living.median())

housing_data['bedrooms'] = housing_data['bedrooms'].fillna(median_bedroom)
housing_data['bathrooms'] = housing_data['bathrooms'].fillna(median_bathrooms)
housing_data['sqft_living'] = housing_data['sqft_living'].fillna(median_sqft_living)

housing_data.head(30)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,condition,sqft_above,sqft_basement,yr_built
0,313000.0,3.0,1.50,1980.0,7912,1.5,3,1340,0,1955
1,2384000.0,5.0,2.50,1980.0,9050,2.0,5,3370,280,1921
2,342000.0,3.0,2.00,1930.0,11947,1.0,4,1930,0,1966
3,420000.0,3.0,2.25,2000.0,8030,1.0,4,1000,1000,1963
4,550000.0,4.0,2.50,1940.0,10500,1.0,4,1140,800,1976
5,490000.0,2.0,1.00,880.0,6380,1.0,3,880,0,1938
6,335000.0,2.0,2.00,1350.0,2560,1.0,3,1350,0,1976
7,482000.0,4.0,2.50,2710.0,35868,2.0,3,2710,0,1989
8,452500.0,3.0,2.00,2430.0,88426,1.0,4,1570,860,1985
9,640000.0,4.0,2.00,1520.0,6200,1.5,3,1520,0,1945
10,463000.0,3.0,1.75,1710.0,7320,1.0,3,1710,0,1948
11,1400000.0,3.0,2.50,2920.0,4000,1.5,5,1910,1010,1909
12,588500.0,3.0,1.75,2330.0,14892,1.0,3,1970,360,1980
13,365000.0,3.0,1.00,1090.0,6435,1.0,4,1090,0,1955
14,1200000.0,5.0,2.75,2910.0,9480,1.5,3,2910,0,1939
15,242500.0,3.0,1.50,1200.0,9720,1.0,4,1200,0,1965
16,419000.0,3.0,1.50,1570.0,6700,1.0,4,1570,0,1956
17,367500.0,4.0,3.00,3110.0,7231,2.0,3,3110,0,1997
18,257950.0,3.0,1.75,1370.0,5858,1.0,3,1370,0,1987
19,275000.0,3.0,1.50,1180.0,10277,1.0,3,1180,0,1983
20,750000.0,3.0,1.75,2240.0,10578,2.0,5,1550,690,1923
21,435000.0,4.0,1.00,1450.0,8800,1.0,4,1450,0,1954
22,626000.0,3.0,2.25,1750.0,1572,2.5,3,1470,280,2005
23,612500.0,4.0,2.50,2730.0,12261,2.0,3,2730,0,1991
24,495000.0,4.0,1.75,1600.0,6380,1.0,3,1130,470,1959
25,285000.0,3.0,2.50,2090.0,10834,1.0,4,1360,730,1987
26,615000.0,3.0,1.75,2360.0,7291,1.0,4,1360,1000,1948
27,698000.0,4.0,2.25,2200.0,11250,1.5,5,1300,900,1920
28,675000.0,5.0,2.50,2820.0,67518,2.0,3,2820,0,1979
29,790000.0,3.0,2.50,2600.0,4750,1.0,4,1700,900,1951

Made the regression_model for prediction using LinearRegression

In [5]:
regression_model = linear_model.LinearRegression()
regression_model.fit(housing_data[['bedrooms','bathrooms','sqft_living','sqft_lot','floors','condition','sqft_above','sqft_basement','yr_built']],housing_data.price)

LinearRegression()

Predicted the data from the Excel

In [7]:
predict_dataset= pd.read_excel(r'/housepredd.xlsx')
prediction = regression_model.predict(predict_dataset)
prediction

array([ 220694.29837095, 1082107.47697025,  521854.01441327,
        557997.83844955,  454500.56775907,  290826.80657874,
        314126.3072842 ,  637436.27674719,  579512.98076023,
        395927.94466285,  470149.30991734])

Added predicted data and converted it into excel

In [18]:
predict_dataset['Prices'] = prediction
predict_dataset.to_excel('final_prediction.xlsx', index=False)